# The PC4 neighborhood for which ev flexibility metrics need to be calculated.
pc4 = 1055

# The duration of the simulation timestep. PTU is used as a term in the energy domain to show the smallest increment
# of time on which energy production and consumption is matched.
# Adding this field is optional.
# Default: 15 minutes.
ptu-duration-minutes = 15

# The duration of congestion in PTU durations. Expects a list of integer numbers.
congestion-durations-ptu = [16, 20]

# The duration of the flex window in PTU durations. Expects a list of integer numbers. If ptu-duration-minutes=15 then 4 equals to 15 * 4 = 60 minutes.
flex-window-durations-ptu = [48, 72]

# Flex window always starts relative to the congestion start. This field sets how many PTU's the flex window starts before congestion start.
flex-window-start-before-congestion-start-ptu = 4

# The date and times at which a congestion start should be simulated. Either this field or table 'congestion-starts-iterate-until' may be set. If both are set, this field takes precedence.
congestion-start-moments = [2020-06-01T01:00:00Z, 2020-06-01T03:00:00Z, 2020-06-01T04:00:00Z]

[congestion-starts-iterate-until]
# The first date and time at which a congestion moment starts.
first-congestion-start = 2020-06-01T00:45:00Z

# New congestion moments are calculated until this date and time is reached.
congestion-start-until = 2020-06-01T01:00:00Z

# The increment of time to calculate the next congestion moment
next-congestion-after-minutes = 60

[input]
# The charge session information.
charge-sessions-path-parquet = "./wp4_shifted_flexible_profiles/input/cleaned/20230616 ChargeSessionsPrivateCharging.parquet"
# The energy profiles which belong to each charge session.
energy-profiles-path-template-parquet= "./wp4_shifted_flexible_profiles/input/cleaned/20230719_charge_session_energy_profiles/chargesessionprofile_pc4_year_{pc4}.parquet"

[output]
# The start of the output profile.
profile-start = 2020-06-01T00:00:00Z
# The end of the output profile.
profile-end = 2020-06-15T00:00:00Z

[output.baseline-profiles]
# The file format to use for output files. Options are parquet and csv.
file-format = "csv"
# Where to save the baseline profiles. Expects a directory.
output-dir = "output_shifted_profiles/baselines/"
# Output is in CSV file and this parameter sets the chosen seperator character.
# Ignored when other files types are used
csv-seperator = ';'
# Output is in CSV file and this parameter defines if the headerline is included. Expects a boolean value 'true' or 'false'.
# Ignored when other files types are used
csv-include-headerline = true
# Output is in CSV file and this parameter defines the token for the decimal sign. Usually is '.' but for Dutch regions ',' may be used.
# Ignored when other files types are used
csv-decimal-sign = ','

[output.shifted-profiles]
# The file format to use for output files. Options are parquet and csv.
file-format = "csv"
# Where to save the baseline profiles. Expects a directory.
output-dir = "output_shifted_profiles/shifted/"
# Output is in CSV file and this parameter sets the chosen seperator character.
# Ignored when other files types are used
csv-seperator = ';'
# Output is in CSV file and this parameter defines if the headerline is included. Expects a boolean value 'true' or 'false'.
# Ignored when other files types are used
csv-include-headerline = true
# Output is in CSV file and this parameter defines the token for the decimal sign. Usually is '.' but for Dutch regions ',' may be used.
# Ignored when other files types are used
csv-decimal-sign = ','
